id: PE620806A
initial_creation_type: input
source_metadata:
  title: Replies to Questions
  language: pt
  description: 'A selection of replies, responses or answers to questions (dris lan):'
  volume:
    df299a2aaf7f49c2b9a9715f291f1cd3:
      title: Advice for Hor Özer
      parent: General
    18837afa42384326948576ba6c248f1e:
      title: Khandro's Plea
      parent: General
    aac1f5df626444a8b5e3df3ef10c1663:
      title: The Pointing-the-Staff Instruction
      parent: General
created_at: '2022-03-01T05:25:02.268416'
last_modified_at: '2022-03-01T05:25:02.268418'
